- hosts: all
  connection: httpapi
  gather_facts: False
  tasks:

    - name: Query a resource
      register: _contrail_vpc
      contrail:
        name: VPCB1
        type: virtual-network
        domain: default-domain
        project: vCenter
        state: query
      
    - name: Print API request status code (integer)
      debug:
        var: _contrail_vpc.status_code

    - name: Print API request response (JSON)
      debug:
        var: _contrail_vpc.content

